### PR TITLE
Make all the help into rowsets

### PR DESCRIPTION
**Pull request by davidfetter**
...so other tools can see them more easily.

### CODE REVIEW

**Comment by davidfetter** [comment]
#321 is included in this patch.

**Comment by petere** [comment]
Unclear why this is wanted. Why does a tool need to process the help in an automated way?

**Comment by davidfetter** [comment]
For example, [this](https://github.com/davidfetter/pgbouncer_wrapper)

**Comment by davidfetter** [comment]
Ping!

**Comment by petere** [comment]
I'm rejecting this. Help information is not data.

**Comment by davidfetter** [comment]
Perhaps I was unclear as to what I attempted to accomplish.

pgbouncer commands represent, in some sense, a schema wherein there are functions some of which return sets, or one could look at them as an API. I was attempting to make said schema/API available to other software of which my `pgbouncer_wrapper` and Crunchy Data's `pgbouncer_fdw` are two examples. What I've been doing up to this point is groveling through the `pgbouncer` source using a Perl program that could be generously described as being composed of chewing gum and baling wire in order to unearth this schema/API.

Would you consider a patch set that implements a different approach to this issue? Two approaches I've considered are:
- Add one function called `describe_api` that sends back something along the lines of a `JSON`blob describing enough of those functions in order for other software to make reasonably correct inferences about what is available.
- Expose more catalog-like information in a more catalog-like form, the extreme end of which would include `information_schema`. This seems like an enormous amount of work for very little benefit.

**Pull request closed without merging**
