### PR TITLE
Proposal to fix #1103 [problem with pool_list and put_in_order]

### LINKED ISSUE #1103: FATAL @src/objects.c:420 in function put_in_order(): put_in_order: found existing elem
Looks identical to issue #968

Today I've upgraded pgbouncer from 1.22.1-1.pgdg22.04+1 to 1.23.0-1.pgdg22.04+1 via `apt`.

1.5h after the upgrade I had this in the logs:

    [...] FATAL @src/objects.c:420 in function put_in_order(): put_in_order: found existing elem

 and pgbouncer died.

### PR DESCRIPTION
**Pull request by dmitry-lipetsk**
Hello,

It is an implementation of my idea to fix an issue #1103.

**Description**

PgCredentials::pool_list is useless and incorrect.

get_pool must work with global pool_list and must check Credentials names (not pointers). The second thing is important because we can have multiple Credentials with one name.

### CODE REVIEW

**Comment by dmitry-lipetsk** [comment]
Hello,

I created pytest with a demonstration of a problem in #1103 but I do not understand where I can add it.

Could someone point me? Thanks!

```py
def test_issue_1103(
    bouncer,
):
    """
    Check that the pgbouncer handles correctly multiple credentials with one name (isue #1103).
    """

    config = f"""
        [databases]
        * = host={bouncer.pg.host} port={bouncer.pg.port} user=postgres min_pool_size=2
        [pgbouncer]
        listen_addr = {bouncer.host}
        listen_port = {bouncer.port}

        auth_type = md5
        auth_file = {bouncer.auth_path}
        auth_query = SELECT usename, passwd FROM pg_shadow where usename = $1
        auth_user = postgres
        auth_dbname = postgres
        admin_users = pswcheck
        logfile = {bouncer.log_path}
    """

    with bouncer.run_with_config(config):
        # Let's get an error "no such user"
        print("POINT #001")
        with pytest.raises(psycopg.OperationalError, match="no such user"):
            bouncer.conn(dbname="dummydb2", user="dummyuser2", password="dummypswd2")
        # Let's wait a few seconds to allow pgbouncer to crash in put_in_order
        time.sleep(5)
        # Now we will try to connect with OK parameters
        print("POINT #002")
        with bouncer.conn(dbname="p3", user="postgres", password="asdasd") as cn:
            with cn.cursor() as cur:
                cur.execute("select 1")

    print("OK!")

```

**Comment by JelteF** [comment]
Thank you for this fix. You can put that the pytest test function somewhere in the `test/test_auth.py` file.

**Comment by dmitry-lipetsk** [comment]
> FAILED test/test_auth.py::test_qa_gh1103__put_in_order - psycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 10208 failed: FATAL:  not allowed

It is difficult to answer on "what is happen?" without PR #1105.

**Comment by dmitry-lipetsk** [comment]
Done.

**Comment by JelteF** [comment]
Thank you for the test and showing me what the problem area of the code was. I decided to fix this pool_list problem a bit differently in #1120, but I included your test there. 

Closing this one in favor of #1120 

PS. I'll try to look at your other PRs soon-ish

**Pull request closed without merging**
