### PR TITLE
Enable ccache on Travis CI to speed up builds

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This will speed up the builds on Travis CI 🏃‍♂️

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hello @petere, do you have a chance to take a look at this PR?

Though I noticed #558 was opened, before the migration was done with enough tests and verification, I believe this will still be useful ;)

**Comment by petere** [comment]
Yeah, it appears that Travis CI isn't quite dead yet. I found this documentation https://docs.travis-ci.com/user/caching/#ccache-cache, which is a bit different from your proposal. Any thoughts?

**Comment by PeterDaveHello** [comment]
@petere it's actually not so different, I defined cache mechanism in list because sometimes we might need multiple, `cache: ccache` or `cache: packages` won't do so. Does this sound fair to you 😄

**Comment by petere** [comment]
This is obsolete now.

**Comment by PeterDaveHello** [comment]
@petere isn't this still useful?

**Pull request closed without merging**
