### PR TITLE
applicationname_add_host options for set application name

### PR DESCRIPTION
**Pull request by DanteG41**
Add an address or hostname to the application name. This is useful when using a connection to a bouncer on a localhost or a scheme with several pgbouncer.

### CODE REVIEW

**Comment by petere** [comment]
Please explain in more detail, give examples, etc.

**Comment by DanteG41** [comment]
I think the diagram will explain it better.

pgbouncer patch explain

**Comment by msirovy** [comment]
This could be very usefull

**Comment by JelteF** [comment]
applicationname_add_host originally had the purpose of still being able to show the IP of the client in postgres logs when PgBouncer and the client are on different nodes. The usage you're trying to add here, isn't that. Because the client and PgBouncer in your diagram would have the same IP, so looking at IPs in postgres logs will show the correct IP. So it's not completely clear what benefit this has over that.

**Comment by JelteF** [comment]
Closing this, since there was no response for a long time.

**Pull request closed without merging**
