### PR TITLE
Convert all stats from INT8 -> NUMERIC(20, 0)

### PR DESCRIPTION
**Pull request by stanhu**
Internally these statistics are stored as unsigned 64-bit values,
but the PostgreSQL INT8 types can only express signed 64-bit values.
Convert all the stats to NUMERIC(20, 0) to avoid losing data.

Closes #360

### CODE REVIEW

**Comment by stanhu** [comment]
@petere Would you mind reviewing?

**Comment by stanhu** [comment]
@petere Friendly ping. We got bit by recently by a problem with not having metrics for a subset of our PgBouncer hosts. Can we look into rolling this in soon?

**Comment by petere** [comment]
I want to go through all the admin and stats commands and check for similar data type mismatch/overflow problems. I think there are a few more. It will need a bit more time.

**Comment by petere** [comment]
a fix has been committed

**Comment by stanhu** [comment]
@petere Thanks, could you cut a new release for PgBouncer?

**Comment by petere** [comment]
yes :)

**Pull request closed without merging**
