### PR TITLE
Fix issue #90: pgbouncer crashes if auth_query user is added to auth_file

### PR DESCRIPTION
**Pull request by qris**
When a user is auto-added to pgBouncer using `auth_query` (by `add_db_user`), their pools are also added to the global pool_list.  If the user is then added to `auth_file` (e.g. because of #59), pgBouncer creates a new user object with the same name (in `add_user`).

Then, when it tries to find a pool for this user, and doesn't (because they are newly created, so their own pool list is empty), it calls new_pool to create one, which tries to add it to the global pool list
again (using `put_in_order`), which aborts (kills the process) because the same username (different PgUser object) and DB name are already in the pool.

This patch appears to fix the crash, but is only lightly tested, and I'm not sure whether we are supposed to remove the original user from the db list, and/or update the global pool entry to point to the new PgUser object, or whether it's OK to return a db pool entry from get_pool.

### CODE REVIEW

**Comment by erthalion** [comment]
I'm a bit surprised by the lack of commentaries about this PR. Of course the described issue is probably not the biggest one, but definitely quite annoying.

About the PR itself, maybe it would be better to adjust this even earlier? If I understand correctly, the problem originates from `forced_user` being created without checking, if a user with the same `db`, `name` already exists. Then if we will do something like this:

```diff
 PgUser *force_user(PgDatabase *db, const char *name, const char *passwd)
 {
        PgUser *user = db->forced_user;

+       if (!user) {
+               user = find_user(name);
+       }
+
        if (!user) {
                user = slab_alloc(user_cache);
                if (!user)
```

we will get the `forced_user` from an existing one with correct `pool_list`.

**Comment by PierreDucroquet** [comment]
I think this issue is also fixed in https://github.com/pgbouncer/pgbouncer/pull/393 along with other crashes, but it was never merged.

**Comment by jhg03a** [comment]
Any chance this could be merged?  This is a much smaller fix than all the pieces of #393 and addresses a key issue that's been broken for years now.

**Comment by JelteF** [comment]
I think this should be fixed now. At least issue #90 has been closed for a long time, and #1052 should have fixed any other similar issues.

**Pull request closed without merging**
