### PR TITLE
fix : #285 , fix :  #353

### PR DESCRIPTION
**Pull request by achix**
This is patch that fixes issue https://github.com/pgbouncer/pgbouncer/issues/285 . This has been tested in production for quite some months and works correctly.

### CODE REVIEW

**Comment by svb007** [comment]
Do you have any idea why the first two patches have been rejected?

**Comment by achix** [comment]
> Do you have any idea why the first two patches have been rejected?

The PR is still open. I guess I'll have to ping Peter again at the next pgconf.eu . Maybe I added two many fixes in the same patch. One other reason might be that the MAX_USERNAME (3rd) patch was for a find for which Peter followed a different solution.

**Comment by petere** [comment]
The issues #285 and #353 mentioned in the title have been fixed, so I'm closing this PR.

The changes in `check_fast_fail()` don't seem to relate to anything discussed here, so if they are still relevant please open a new issue and let's have a focused discussion there.

**Comment by achix** [comment]
Thank you Peter,
see you in Milan, pgconf.eu I hope!

**Comment by achix** [comment]
Just a question,
any chances this commit will be included in pgbouncer 1.12 ?

**Comment by petere** [comment]
I'm not sure what you mean. This PR is closed for the reasons given. If you have anything else from this PR that you want considered, please explain.

**Comment by achix** [comment]
Sorry for the confusion, I mean to ask about your commits not mine :
I see
https://github.com/pgbouncer/pgbouncer/commit/645a4c5a6159e69cfa4bf225fe911d5116502e70
(Prevent too long user name or password from client) was included in
PgBouncer 1.11.
However, this commit :
https://github.com/pgbouncer/pgbouncer/commit/b30b49f16d718339f0f7ffee408c48b376c0eb81
(Fix issue with PAM users losing their password ) was not included in
PgBouncer 1.11 so I was wondering if this will be in the next release (1.12)
Thanks

**Comment by petere** [comment]
Yes, whatever is in the master branch will be in the next release.

**Pull request closed without merging**
