### PR TITLE
Add application_name to SHOW CLIENTS/SERVERS/SOCKETS output

### PR DESCRIPTION
**Pull request by stevenwinfield**
Implements the feature request at https://github.com/pgbouncer/pgbouncer/issues/167

### CODE REVIEW

**Comment by dtseiler** [comment]
+1, would be really helpful

**Comment by dtseiler** [comment]
Still holding out hope we can get this so we don't have to keep our custom build. @petere!

**Comment by infraweavers** [comment]
@petere This is a really useful feature! Is there any chance of getting this PR merged in?

**Comment by JelteF** [comment]
This looks pretty useful, and low maintenance. If you used different application names this allows you to find out very easily what clients/server connections are active.

**Review by JelteF — APPROVED** [review]

**Review by shafinshah36 — COMMENTED** [review]
src/admin.c

**Review by shafinshah36 — APPROVED** [review]
src/admin.c

**Pull request merged**
