### PR TITLE
v1.23.1

### PR DESCRIPTION
**Pull request by JelteF**
A log file was added by @emelsimsek when updating submodules previously. This commit is not on master, so I guess something went wrong with the release flow last time. I removed it in a commit. I branch the `stable-1.23` branch of of the `pgbouncer_1_23_0` tag.

CentOS 7 build is failing but that seems related to CentOS 7 finally being EOL. So I think it's safe to ignore that failure. (I'll create a new PR to remove the build target on master)

SSL tests related to client side certs are failing on Alpine. My guess is that that has the same cause as: https://github.com/pgbouncer/pgbouncer/issues/1031 So I don't think this needs to block the release.

### CODE REVIEW

**Review by eulerto — COMMENTED** [review]
You forgot to change the version in `configure.ac`: 1.23.1

Oops, fixed now.

**Comment by JelteF** [comment]
> You forgot to change the version in `configure.ac`: 1.23.1

Oops, fixed now.

**Review by eulerto — APPROVED** [review]
LGTM

**Review by emelsimsek — APPROVED** [review]

**Comment by JelteF** [comment]
> > You forgot to change the version in `configure.ac`: 1.23.1
> 
> Oops, fixed now.

Ugh, turns out I didn't actually push this that fix to the branch and only had it fixed locally... Fixed now by manually pushing a tiny commit to stable-1.23 and adding a new `pgbouncer_1_23_1-fixed` tag.

**Pull request merged**
