### PR TITLE
Don't prematurely release the server in the middle of a parse/bind/execute on the unnamed statement.

### PR DESCRIPTION
**Pull request by adunstan**
We found this feature useful especially for drivers like Go. It has been tested in the field and found to work seamlessly on our client's site.

### CODE REVIEW

**Comment by markokr** [comment]
Should be fixed in master, please test.

**Comment by adunstan** [comment]
No, unfortunately this has not fixed the issue that my patch addressed.

Here is a test case written in Go that exercises the issue

Expected output:

[andrew@emma pgbouncer-dev]$ go run testme.go 
ok, connected
relname is pg_statistic
relname is pg_type
relname is pg_authid

Actual output:

[andrew@emma pgbouncer-dev]$ go run testme.go 
ok, connected
2015/08/14 12:29:46 pq: unnamed prepared statement does not exist
exit status 1

Program:

package main

import (
	"database/sql"
        "log"
	_ "github.com/lib/pq"
        "fmt"
)

func main() {
	db, err := sql.Open("postgres", "dbname=postgres port=6432 sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("ok, connected")
	rows, err := db.Query("SELECT relname FROM pg_class where relkind = $1 limit 3", "r")
    if err != nil {
            log.Fatal(err)
    }
    defer rows.Close()
    for rows.Next() {
            var name string
            if err := rows.Scan(&name); err != nil {
                    log.Fatal(err)
            }
            fmt.Printf("relname is %s\n", name)
    }
	if err := rows.Err(); err != nil {
            log.Fatal(err)
    }
}

**Comment by markokr** [comment]
What does the driver actually do?  To me it seems like driver bug - it uses Sync while it should use Flush.

**Comment by markokr** [comment]
Ok, I reread the commit: "parse/describe/sync followed by bind/execute ... sync".

If there is really good explanation why driver needs Sync there and not Flush I may reconsider, but until then I see this as example of buggy driver.

**Comment by adunstan** [comment]
What's buggy about it? It doesn't seem to be counter to the protocol as far as I can see, and I know of at least 2 drivers (Go and Rust) that work this way, even though libpq does not. It works perfectly when there is no pgbouncer proxy - Postgres itself handles it just fine.

**Comment by jberkus** [comment]
marko: Go is one of the more popular languages to use with PostgreSQL, so the non-functionality of pgbouncer with Go is not a trivial issue.  Do you have a specific reason why they shouldn't be using Sync which would be persuasive, instead of just "I don't like it"?  Given that it works fine with direct connections to PostgreSQL.

**Comment by markokr** [comment]
Hint: the answer to Sync is ReadyForQuery which also contains transaction state.

When pgbouncer sees ReadyForQuery:no-tx-open, then why does it need to look at the plan name to know protocol state?  In fact this means there is an ad-hoc meta-protocol in top of regular V3 protocol.

> so the non-functionality of pgbouncer with Go is not a trivial issue.

It will work perfectly fine with pgbouncer in session-pooling mode. If you want transaction pooling, your app and driver need to cooperate with pgbouncer.

PgBouncer is not a place for hacks to work around problems with non-cooperating apps&drivers.

**Pull request closed without merging**
